on:
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout

    - name: Push files
      uses: SamKirkland/FTP-Deploy-Action
      with:
        server: skayser.de
        username: skayser-de
        password: ${{ secrets.FTP_PASSWORD }}
        log-level: verbose
